include(CMakeParseArguments)

option(USE_RUNTIME_INSTALL_PREFIX "Use runtime installation directory" ON)

# Path configuration
if (UNIX)
	if (USE_RUNTIME_INSTALL_PREFIX)
		set(CMAKE_INSTALL_PREFIX "/")
	endif()
	set(MINT_RUNTIME_INSTALL_DIR "bin")
	set(MINT_LIBRARY_INSTALL_DIR "lib")
	set(MINT_HEADERS_INSTALL_DIR "usr/include")
	set(MINT_MODULES_INSTALL_DIR "${MINT_LIBRARY_INSTALL_DIR}/mint")
	set(MINT_SCRIPTS_INSTALL_DIR "${MINT_LIBRARY_INSTALL_DIR}/mint-scripts")
	set(MINT_CMAKE_INSTALL_DIR "usr/share/cmake")
else()
	if (USE_RUNTIME_INSTALL_PREFIX)
		set(CMAKE_INSTALL_PREFIX "C:/")
	endif()
	set(MINT_RUNTIME_INSTALL_DIR "mint/bin")
	set(MINT_LIBRARY_INSTALL_DIR "mint/lib")
	set(MINT_HEADERS_INSTALL_DIR "mint/include")
	set(MINT_MODULES_INSTALL_DIR "${MINT_LIBRARY_INSTALL_DIR}/mint")
	set(MINT_SCRIPTS_INSTALL_DIR "${MINT_LIBRARY_INSTALL_DIR}/mint-scripts")
	set(MINT_CMAKE_INSTALL_DIR "mint/share/cmake")
endif()
