name: C/C++ CI Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get -y install bison libgtest-dev libicu-dev libmagic-dev
        cd /usr/src/gtest/
        sudo cmake -DBUILD_SHARED_LIBS=ON
        sudo make
        sudo cp lib/*.so /usr/lib
    - name: configure
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: make
      run: |
        make
        sudo make install
      working-directory: ./build
    - name: run tests
      run: ctest
      working-directory: ./build
    - name: run library tests
      run: /bin/mint ./test.mn
      working-directory: ./tests
