name: C/C++ CI Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt -y install bison autoconf-archive libmagic-dev
        git clone https://github.com/microsoft/vcpkg.git
        pushd vcpkg
        ./bootstrap-vcpkg.sh
        popd
    - name: Install GCC 15
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-15 g++-15
    - name: configure
      run: |
        export VCPKG_ROOT=./vcpkg
        export PATH=$VCPKG_ROOT:$PATH
        cmake --preset=vcpkg -DCMAKE_BUILD_TYPE=Release
      env:
        CC: gcc-15
        CXX: g++-15
    - name: make
      run: |
        cmake --build build --target all
        sudo cmake --build build --target install
    - name: run tests
      run: ctest
      working-directory: ./build
    - name: run library tests
      run: /bin/mint ./test.mn
      working-directory: ./tests
