name: C/C++ CI macOS

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew update
        brew install bison autoconf automake autoconf-archive libmagic

        git clone https://github.com/microsoft/vcpkg.git
        pushd vcpkg
        ./bootstrap-vcpkg.sh
        popd

    - name: Configure
      run: |
        export VCPKG_ROOT=$PWD/vcpkg
        export PATH=$VCPKG_ROOT:$PATH
        export CPATH="$(brew --prefix)/include"
        export LIBRARY_PATH="$(brew --prefix)/lib"

        cmake --preset=vcpkg \
              -DBISON_EXECUTABLE="$(brew --prefix bison)/bin/bison" \
              -DMINT_COPY_MODULE_SOURCES_TO_BUILD_DIR=ON \
              -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        export CPATH="$(brew --prefix)/include"
        export LIBRARY_PATH="$(brew --prefix)/lib"

        cmake --build build

    - name: Run tests
      working-directory: ./build
      run: ctest

    - name: Run library tests
      working-directory: ./tests
      env:
        MINT_LIBRARY_PATH: ${{ github.workspace }}/build/out/lib/mint
      run: ${{ github.workspace }}/build/out/bin/mint ./test.mn
