name: C/C++ CI Windows

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        choco install -y winflexbison3
        git clone https://github.com/microsoft/vcpkg.git
        pushd vcpkg
        .\bootstrap-vcpkg.bat
        popd
    - name: configure
      run: |
        $env:VCPKG_ROOT = ".\vcpkg"
        $env:PATH = "$env:VCPKG_ROOT;$env:PATH"
        cmake --preset=vcpkg -G "Visual Studio 18 2026" -DCMAKE_BUILD_TYPE=Release
    - name: make
      run: |
        cmake --build build --target ALL_BUILD --config Release
        cmake --build build --target INSTALL --config Release
    - name: run tests
      run: ctest
      working-directory: ./build
    - name: run library tests
      run: C:\mint\bin\mint .\test.mn
      working-directory: ./tests
