name: C/C++ CI Windows

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        choco install -y winflexbison3
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake -DBUILD_SHARED_LIBS=ON ..
        cmake --build . --target INSTALL --config Debug
        cmake --build . --target INSTALL --config Release
    - name: configure
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_POLICY_DEFAULT_CMP0074=NEW ..
      env:
        GTEST_ROOT: "C:\\Program Files (x86)\\googletest-distribution"
    - name: make
      run: |
        cmake --build . --target ALL_BUILD --config Release
        cmake --build . --target INSTALL --config Release
      working-directory: ./build
    - name: run tests
      run: |
        copy "C:\Program Files (x86)\googletest-distribution\bin\*.dll" -destination .
        .\test-ast.exe
        .\test-compiler.exe
        .\test-debug.exe
        .\test-memory.exe
        .\test-scheduler.exe
        .\test-system.exe
        C:\mint\bin\mint ..\..\..\tests\test.mn
      working-directory: ./build/bin/Release
